"""currency definitions

Revision ID: 0002
Revises: 0001_baseline
Create Date: 2026-08-27 22:18:11.982642

REVIEW CHECKLIST -- every migration on this project is read by a human before it runs:
  * No DROP of a table or column carrying financial state without explicit human approval.
  * Monetary columns are integer minor units (DECISION S4-1): `amount_minor BIGINT` plus
    `currency`, `scale` and `currency_def_version`. Never NUMERIC/DECIMAL as authoritative
    money, never float.
  * Constraints carry deterministic names from the `app.db.base` naming convention.
  * `downgrade()` is honest: if a step cannot be reversed without losing financial
    history, it raises rather than pretending.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | None = "0001_baseline"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currency_definitions",
        sa.Column("currency", sa.CHAR(length=3), nullable=False),
        sa.Column("currency_def_version", sa.String(length=32), nullable=False),
        sa.Column("scale", sa.SmallInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "currency ~ '^[A-Z]{3}$'", name=op.f("ck_currency_definitions_currency_format")
        ),
        sa.CheckConstraint(
            "currency_def_version <> ''", name=op.f("ck_currency_definitions_def_version_not_empty")
        ),
        sa.CheckConstraint(
            "scale BETWEEN 0 AND 8", name=op.f("ck_currency_definitions_scale_range")
        ),
        sa.PrimaryKeyConstraint(
            "currency", "currency_def_version", name=op.f("pk_currency_definitions")
        ),
        sa.UniqueConstraint(
            "currency",
            "currency_def_version",
            "scale",
            name=op.f("uq_currency_definitions_currency_currency_def_version_scale"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("currency_definitions")
    # ### end Alembic commands ###
